const express = require('express')

const authRouter = require('./auth/auth.router')
const verifyEmail = require('./verifyEmail/emailVerifyRoute')
const tokenRouter = require('./orignaltoken/originalToken.router')
const auctionRouter = require('./auction/auction.router')
const orderRouter = require('./order/order.router')
const userRouter = require('./user/user.router')
const cartRouter = require('./cart/cart.router')
const bidRouter = require('./bid/bid.route')
const colorRouter = require('./colors/colors.router')
const replicaRouter = require('./replicas/replicas.router')
const replicaPriceRouter = require('./replicaPrice/replicaPrice.router')
const proposeRouter = require('./propose/propose.route')
const fwordRouter = require('./fWord/fWord.route')
const AdminAddressRouter = require('./adminaddress/adminAdress.route')
const TaxRouter = require('./TaxIdentifiers/taxIdentifiers.route')
const ShipmentRouter = require('./Shipment/shipment.route')
const adminTokenRouter = require('./adminToken/adminToken.route')
const searchRouter = require('./search/search.route')
const hashRouter = require('./smartContractHash/smartContractHash.route')
const proposedhashRouter = require('./proposedHash/proposedHash.route')

const api = express.Router()

api.use('/',verifyEmail )
api.use('/', authRouter)
api.use('/users', userRouter)
api.use('/original/token', tokenRouter)
api.use('/auction/token', auctionRouter)
api.use('/order', orderRouter)
api.use('/cart', cartRouter)
api.use('/bid', bidRouter)
api.use('/colors', colorRouter)
api.use('/replica/token', replicaRouter)
api.use('/replicaPrice', replicaPriceRouter)
api.use('/propose/token', proposeRouter)
api.use('/fword', fwordRouter)
api.use('/address', AdminAddressRouter)
api.use('/tax', TaxRouter)
api.use('/shipment', ShipmentRouter)
api.use('/admin/token', adminTokenRouter)
api.use('/search', searchRouter)
api.use('/hash', hashRouter)
api.use('/proposed/hash', proposedhashRouter)


module.exports = api;